apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: efsudp8r58f7ke
    access: proxy
    url: host.docker.internal:5432
    database: DT-MAIN
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: true